### ISSUE TITLE
[UPDATE] 챌린지 CSS 구성 및 오류 수정

### ISSUE THREAD

**Issue by hani2525** [seolhwacode/DaDoc-Server#154]
* 챌린지 페이지 register_form, update_form 관련 CSS 수정 및 유효성 검사 추가
* 챌린지 페이지 관련 alert 처리
* 페이지 이동 오류 수정

**Comment by seolhwacode** [comment]
#159 오류 수정은 X, css 추가 완료
pr & merge ok

**Comment by seolhwacode** [comment]
결국 전부 해결 되지는 않았음
