### ISSUE TITLE
[ADD] 챌린지 참가 신청 기능 추가

### ISSUE THREAD

**Issue by hani2525** [seolhwacode/DaDoc-Server#36]
* detail 페이지에서 챌린지 참가 신청 기능을 추가
* detail 페이지에 버튼을 누르면 모달이 나온다 -> 모달에서 약관사항 확인 후 체크하고 확인 버튼을 누르면 참가 신청 완료

**Comment by seolhwacode** [comment]
#39 pull request & merge 완료
