### ISSUE TITLE
[ADD] 챌린지 메인 페이지 - 상세보기 버튼 추가 및 관련 기능 구현  

### ISSUE THREAD

**Issue by hani2525** [seolhwacode/DaDoc-Server#79]
* 상세보기 버튼 추가 : 상세보기 버튼을 누르면 detail페이지로 넘어갑니다.
* 관련 기능 : 챌린지 시작일이 지났으면 버튼은 비활성화 되고 버튼안의 텍스트는 '지난 챌린지' 로 변경됩니다.

**Comment by seolhwacode** [comment]
#85 pr & merge
